project architecture
GalinaGitH/java-explore-with-me pull request #1
Opened 2022-11-13 13:24 UTC by GalinaGitH

2022-11-23 20:27 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-11-23 20:27 UTC, FanaticFiz commented on ewm/src/main/java/ru/practicum/ewm/EwmApplication.java
> +public class EwmApplication {
Самый мою любимы класс! 
В нём всегда всё правильно! )))

Привет!

2022-11-23 20:27 UTC, FanaticFiz commented on ewm/src/main/java/ru/practicum/ewm/category/CategoryServiceImpl.java
> +        List<EventCategory> categories = (List<EventCategory>) categoryRepository.findAll();
Зачем же кастовать((List<EventCategory>)... это же всё наше родное, ты всегда знаешь что возвращается из репозитория...

2022-11-23 20:27 UTC, FanaticFiz commented on ewm/src/main/java/ru/practicum/ewm/category/CategoryServiceImpl.java
> +        final EventCategory eventCategory = categoryRepository.findById(catId).orElseThrow(NotFoundException::new);
`NotFoundException::new` очень удобно конечно, но совершенно не информативно!

Надо дать как можно больше информации... что не найдено, добавить id если по нему искали или какой другой параметр по которому искали.

2022-11-23 20:27 UTC, FanaticFiz commented on ewm/src/main/java/ru/practicum/ewm/category/CategoryServiceImpl.java
> +        EventCategory categoryInStorage = categoryRepository.findById(categoryDto.getId()).orElseThrow(NotFoundException::new);
Строка вылезла за 120 символов, нужен перенос!

Да и вообще нужно всегда переносить операции которые мы комбинируем через точку, но новые строки, так будет куда нагляднее...

```
        EventCategory categoryInStorage = categoryRepository.findById(categoryDto.getId())
                                                            .orElseThrow(NotFoundException::new);

```

2022-11-23 20:27 UTC, FanaticFiz commented on ewm/src/main/java/ru/practicum/ewm/category/controller/AdminCategoriesController.java
> +        log.info("Create new category");
Логи для нас... их тоже лучше насыщать информацией, потому что нам же по ним разбираться что идёт не так.
Положи туда модель которая пришла в запросе! Сама себе спасибо скажешь в будущем! ))

2022-11-23 20:27 UTC, FanaticFiz commented on ewm/src/main/java/ru/practicum/ewm/user/User.java
> +    private String name;
В целом во многих местах у тебя хорошо с описанием полей...
Но туту упущено: поле name в БД: `name VARCHAR(255) NOT NULL`

2022-11-23 20:27 UTC, FanaticFiz commented on ewm/src/main/resources/schema.sql
> +    paid        BOOLEAN                                 NOT NULL,
Кажется и выровнено, но как то не до конца!

2022-11-23 20:27 UTC, FanaticFiz commented on ewm/src/main/resources/application.properties
> +server.port=8080
Я рекомендую привыкать к написанию файла свойств для приложения в формате `yaml -> application.yml`

2022-11-23 20:27 UTC, FanaticFiz commented on ewm/src/main/java/ru/practicum/ewm/user/exception/NotFoundException.java
> +public class NotFoundException extends RuntimeException {
Соответственно в классах ексепшенов должен быть конструктор, принимающий строку и транслирующий её в наследуемый класс.

2022-11-23 20:27 UTC, FanaticFiz commented on ewm/src/main/java/ru/practicum/ewm/compilation/CompilationServiceImpl.java
> +        if (pinned != null) {
Еще примеров...
Вот так это может выглядеть:

```
        if (pinned != null) {
            return compilationRepository.findAllByPinned(pinned, PageRequest.of(page, size)).stream()
                                        .map(compilationMapper::toDto)
                                        .collect(Collectors.toList());
        }
        
        return compilationRepository.findAll(PageRequest.of(page, size)).stream()
                                    .map(compilationMapper::toDto)
                                    .collect(Collectors.toList());
```

2022-11-23 20:27 UTC, FanaticFiz commented on ewm/src/main/java/ru/practicum/ewm/event/EventCustomRepository.java
> +public interface EventCustomRepository extends JpaRepository<Event, Long>, JpaSpecificationExecutor<Event> {
О! Интересно. Впервые встречаю критерии в работе студента.
А самой то понятно, нравиться? удобно? 

Как по мне стандартные SQL читаются и понимаются куда лучше.
(Это не призыв к переделыванию)

2022-11-23 20:27 UTC, FanaticFiz commented on ewm/src/main/java/ru/practicum/ewm/event/EventServiceImpl.java
> +        Event event = eventRepository.findByIdAndState(eventId, EventState.PUBLISHED);
Так это... ты же с Optional на короткой ноге...
Возвращай: `Optional<Event> findByIdAndState` и по привычной схеме, ексепшн если не найдено...

2022-11-23 20:27 UTC, FanaticFiz commented on ewm/src/main/java/ru/practicum/ewm/event/EventServiceImpl.java
> +        if (newEventDto.getTitle() != null) {
Прям большой дублирующийся блок кода...
Строки 180-198 и 59-75

2022-11-23 20:27 UTC, FanaticFiz commented on ewm/src/main/java/ru/practicum/ewm/event/EventServiceImpl.java
> +        event.setState(EventState.CANCELED);
Можно заимпортить предварительно статики и получить в коде удобство

`import static ru.practicum.ewm.event.EventState.CANCELED;`
`event.setState(CANCELED);`

2022-11-23 20:27 UTC, FanaticFiz commented on ewm/src/main/java/ru/practicum/ewm/request/RequestServiceImpl.java
> +    public ParticipationRequestDto confirmParticipationRequest(long userId, long eventId, long requestId) {
Переменная `userId` не используется тут?

2022-11-23 20:27 UTC, FanaticFiz commented on ewm/src/main/java/ru/practicum/ewm/request/RequestServiceImpl.java
> +        User user = userRepository.findById(userId).orElseThrow(NotFoundException::new);
И опять же, нашли пользователя и не заиспользовали: `User user` ??

2022-11-23 20:27 UTC, FanaticFiz commented on ewm/src/main/java/ru/practicum/ewm/request/controller/ParticipationRequestController.java
> +        log.info("Confirmation of someone else's application for participation in event (eventId={}) of the userId={}", eventId, userId);
Длинные, длинные строкиииии... ))

2022-11-23 20:27 UTC, FanaticFiz commented on ewm/src/main/java/ru/practicum/ewm/user/ErrorHandler.java
> +        log.info(e.getMessage());
Произошла ошибка, лог должен быть соответствующий `error`
Плюс, желательно залогировать со стек трейсом...
log.error("{}", e.getMessage(), e);

2022-11-23 20:27 UTC, FanaticFiz commented on ewm/src/main/java/ru/practicum/ewm/user/UserRepository.java
> +    User findByEmail(String email);
Через Optional будет удобнее?

2022-11-25 12:04 UTC, GalinaGitH commented on ewm/src/main/java/ru/practicum/ewm/EwmApplication.java
> +public class EwmApplication {
Привет! Да в этот класс я правки не вносила))

2022-11-25 12:04 UTC, GalinaGitH commented on ewm/src/main/java/ru/practicum/ewm/category/CategoryServiceImpl.java
> +        final EventCategory eventCategory = categoryRepository.findById(catId).orElseThrow(NotFoundException::new);
Исправила

2022-11-25 12:05 UTC, GalinaGitH commented on ewm/src/main/java/ru/practicum/ewm/category/controller/AdminCategoriesController.java
> +        log.info("Create new category");
Исправила!Сделала их более информативными

2022-11-25 12:05 UTC, GalinaGitH commented on ewm/src/main/java/ru/practicum/ewm/user/User.java
> +    private String name;
+

2022-11-25 12:07 UTC, GalinaGitH commented on ewm/src/main/resources/application.properties
> +server.port=8080
Не пробовала, но хочу сначала на кошках потренироваться)))боюсь все сломать((( В формате yaml да, выглядит куда более читабельным

2022-11-25 12:07 UTC, GalinaGitH commented on ewm/src/main/java/ru/practicum/ewm/user/exception/NotFoundException.java
> +public class NotFoundException extends RuntimeException {
исправила

2022-11-25 12:07 UTC, GalinaGitH commented on ewm/src/main/java/ru/practicum/ewm/compilation/CompilationServiceImpl.java
> +        if (pinned != null) {
спасибо!скорректировала

2022-11-25 12:10 UTC, GalinaGitH commented on ewm/src/main/java/ru/practicum/ewm/event/EventServiceImpl.java
> +        Event event = eventRepository.findByIdAndState(eventId, EventState.PUBLISHED);
Спасибо за высокую оценку моих достижений в написании кода )))) Буду расти конечно, чтоб быть с Optional на ты)))

2022-11-25 12:10 UTC, GalinaGitH commented on ewm/src/main/java/ru/practicum/ewm/event/EventServiceImpl.java
> +        if (newEventDto.getTitle() != null) {
исправила

2022-11-25 12:11 UTC, GalinaGitH commented on ewm/src/main/java/ru/practicum/ewm/event/EventServiceImpl.java
> +        event.setState(EventState.CANCELED);
Спасибо за помощь в улучшении кода! Внесла корректировки!

2022-11-25 12:11 UTC, GalinaGitH commented on ewm/src/main/java/ru/practicum/ewm/request/RequestServiceImpl.java
> +    public ParticipationRequestDto confirmParticipationRequest(long userId, long eventId, long requestId) {
Уже используется)

2022-11-25 12:12 UTC, GalinaGitH commented on ewm/src/main/java/ru/practicum/ewm/user/ErrorHandler.java
> +        log.info(e.getMessage());
внесла изменения в Handler

2022-11-25 12:12 UTC, GalinaGitH commented on ewm/src/main/java/ru/practicum/ewm/user/UserRepository.java
> +    User findByEmail(String email);
💯

2022-11-25 12:16 UTC, GalinaGitH commented on ewm/src/main/java/ru/practicum/ewm/event/EventCustomRepository.java
> +public interface EventCustomRepository extends JpaRepository<Event, Long>, JpaSpecificationExecutor<Event> {
Решила попробовать что-то новое для себя, нагуглила , применила. Выглядит конечно куда массивнее чем просто кастомный query, но мне показалось все это очень логичным и понятным. И просто интересно очень как это работает)))

2022-11-26 09:07 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-11-26 09:07 UTC, FanaticFiz commented on ewm/src/main/java/ru/practicum/ewm/category/CategoryServiceImpl.java
> +        return categories.stream()
Есть хорошая практика делать отступ перед `return`.

Это выделяет точку выхода из метода визуально.
Есть только одно исключение: если метод начался сразу с return то отступ делать не нужно.

Т.е. твой код может выглядеть вот так:

```
    @Override
    public List<CategoryDto> getCategories(int from, int size) {
        List<EventCategory> categories = categoryRepository.findAll();

        return categories.stream()
                         .map(categoryMapper::toDto)
                         .collect(Collectors.toList());
    }
```

Или вот так:

```
    @Override
    public List<CategoryDto> getCategories(int from, int size) {
        return categoryRepository.findAll().stream()
                                 .map(categoryMapper::toDto)
                                 .collect(Collectors.toList());
    }
```

2022-11-26 09:07 UTC, FanaticFiz commented on ewm/src/main/java/ru/practicum/ewm/category/CategoryServiceImpl.java
> +    public List<CategoryDto> getCategories(int from, int size) {
`int from, int size` не используются!

2022-11-26 09:07 UTC, FanaticFiz commented on ewm/src/main/java/ru/practicum/ewm/compilation/CompilationServiceImpl.java
> +        Compilation compilation = new Compilation(null, newCompilationDto.getTitle(), newCompilationDto.isPinned());
`new Compilation` почему собираем тут? 
А как же наши классы помощники - мапперы?

2022-11-26 09:07 UTC, FanaticFiz commented on ewm/src/main/java/ru/practicum/ewm/compilation/CompilationServiceImpl.java
> +        Compilation compilation = new Compilation(null, newCompilationDto.getTitle(), newCompilationDto.isPinned());
Ну вот так например

```
        List<Event> events = eventRepository.findAllById(compilationDto.getEvents());
        Compilation compilation = Mapper.toNewCompilation(compilationDto, events);
        
        Compilation savedCompilation = repository.save(compilation);
        
        return Mapper.toCompilationDto(savedCompilation);
```

2022-11-26 09:07 UTC, FanaticFiz commented on ewm/src/main/java/ru/practicum/ewm/event/EventServiceImpl.java
> +        return events.stream().map(eventMapper::toShortDto).collect(Collectors.toList());
Даже если помещается в одну строку, лучше переносить на новую строку каждую операцию в цепочке

```
    @Override
    public List<EventShortDto> getEventsOfUser(long userId, int from, int size) {
        int page = from / size;

        return eventRepository.findEventsByInitiator_Id(userId, PageRequest.of(page, size)).stream()
                              .map(eventMapper::toShortDto)
                              .collect(Collectors.toList());
    }
```

2022-11-26 09:07 UTC, FanaticFiz commented on ewm/src/main/java/ru/practicum/ewm/request/RequestServiceImpl.java
> +            throw new NonComplianceWithTheRulesOfParticipationException("Initiator can confirm applications " +
Не думаю что стоило создавать такой ексепшн класс
`NonComplianceWithTheRulesOfParticipationException` 
Стоит подумать - та ситуация которая тут сложилась, под какой из HTTP ответов у нас подпадает, т.е. что мы должны ответить клиенту, это BadRequest ? Conflict? IllegalState?
Ну и использовать соответствующий ексепшн...

2022-11-26 09:07 UTC, FanaticFiz commented on ewm/src/main/java/ru/practicum/ewm/request/RequestServiceImpl.java
> +        List<ParticipationRequest> requests = requestRepository.findAllByRequester_Id(userId);
Я уже много тебе демонстрировал примеров... 
попробуй этот метод самостоятельно оформить как я показывал...

2022-11-26 09:07 UTC, FanaticFiz commented on ewm/src/main/java/ru/practicum/ewm/request/RequestServiceImpl.java
> +    private void updateConfirmedRequests(long eventId, int count) {
А что мы тут делаем?

Нашли event(один запрос) засетили ему одно поле и обновили(второй запрос)

А что мешает написать метод в `eventRepository` который обновляет этот счетчик за один запрос? ))

2022-11-26 09:07 UTC, FanaticFiz commented on ewm/src/main/java/ru/practicum/ewm/user/UserServiceImpl.java
> +            throw new EmailNotUniqueException("Already exist");
`EmailNotUniqueException` вот тоже я бы не заводил прям отдельный эксепшн, это все частные случаи `ConflictEception` вот прям его и кидаем. 
Да конечно мы напишем в сообщении что за конфликт произошел. И этого достаточно.

2022-11-27 06:23 UTC, FanaticFiz approved these changes

2022-11-27 06:23 UTC, FanaticFiz commented on ewm/src/main/java/ru/practicum/ewm/request/RequestServiceImpl.java
> +                .orElseThrow(() -> new NotFoundException("Not found event with id = " + eventId));
Обрати внимание на расположение классов ексепшенов.
Они общие для всех сущностей, а расположены в user.

Надо вынести выше.

2022-11-27 06:23 UTC, FanaticFiz commented on stats/src/main/java/ru/practicum/stats/dto/EndpointHitDto.java
> +@EqualsAndHashCode(of = "id")
В этой сущности же нет поля `id` !!

2022-11-27 06:23 UTC, FanaticFiz commented on stats/src/main/java/ru/practicum/stats/StatsController.java
> +        statsService.addHit(endpointHitDto);
`addHit` возвращает `dto`!

А мы этим не пользуемся...

2022-11-28 08:24 UTC, merged